export const INIT_HOME_DATA = 'INIT_HOME_DATA'
export const FETCHING_HOME_DATA = 'FETCHING_HOME_DATA'
export const FETCHING_HOME_SUCCESS = 'FETCHING_HOME_SUCCESS'
export const FETCHING_HOME_FAILED = 'FETCHING_HOME_FAILED'
